name: sync2cnb.yaml

# 在main分支发生push事件时触发。
on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

# 设置环境变量
env:
  TZ: Asia/Shanghai # 时区（设置时区可使页面中的`最近更新时间`使用时区时间）

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: "Sync to CNB Repository"
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:${{ github.workspace }} \
            -w ${{ github.workspace }} \
            -e PLUGIN_TARGET_URL=${{ secrets.GIT_REPO }} \
            -e PLUGIN_AUTH_TYPE="https" \
            -e PLUGIN_USERNAME=${{ secrets.GIT_USERNAME }} \
            -e PLUGIN_PASSWORD=${{ secrets.GIT_PASSWORD }} \
            -e PLUGIN_FORCE="true" \
            tencentcom/git-sync
